<?php


/**
 * @OA\Info(
 *     title="Laravel API",
 *     version="1.0.0",
 *     description="API documentation generated by Swagger for Laravel."
 * )
 */
namespace App\Http\Controllers\Api;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class TestController extends Controller
{
    /**
     * @OA\Info(
     *     title="Laravel API",
     *     version="1.0.0",
     *     description="API documentation generated by Swagger for Laravel."
     * )
     *
     * @OA\Get(
     *     path="/api/test",
     *     summary="Test endpoint",
     *     description="Returns a simple test response.",
     *     @OA\Response(
     *         response=200,
     *         description="Successful response"
     *     )
     * )
     */
    public function index()
    {
        return response()->json(['message' => 'Test successful']);
    }
}
