name: Deploy Laravel to cPanel via Git

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, bcmath, xml
          coverage: none

      - name: Install Composer dependencies
        run: composer install --no-interaction --prefer-dist --optimize-autoloader

      - name: Push to cPanel Git Repository
        env:
          CPANEL_GIT_REPO: ${{ secrets.CPANEL_GIT_REPO }}
          CPANEL_GIT_USERNAME: ${{ secrets.CPANEL_GIT_USERNAME }}
          CPANEL_GIT_PASSWORD: ${{ secrets.CPANEL_GIT_PASSWORD }}
        run: |
          git remote add cpanel https://${CPANEL_GIT_USERNAME}:${CPANEL_GIT_PASSWORD}@${CPANEL_GIT_REPO}
          git push --force cpanel main

      - name: Run Laravel migrations (optional)
        run: |
          echo "You may need to run migrations manually on cPanel."
